import net.fabricmc.loom.task.AbstractRunTask
import net.fabricmc.loom.task.RemapJarTask

buildscript {
    dependencies {
        classpath "com.google.code.gson:gson:2.12.1"
    }
}

plugins {
    id "java"
    id "fabric-loom" version "1.10.4"
}

group = "agency.highlysuspect"
version = "1.3"

java.toolchain.languageVersion = JavaLanguageVersion.of(21);
tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release = 21
}

sourceSets {
    main
    
    spectatorheads {
        compileClasspath += sourceSets.main.compileClasspath
        runtimeClasspath += sourceSets.main.runtimeClasspath
    }
    
    bobbyallowlist {
        compileClasspath += sourceSets.main.compileClasspath
        runtimeClasspath += sourceSets.main.runtimeClasspath
    }
    
    quickfov {
        compileClasspath += sourceSets.main.compileClasspath
        runtimeClasspath += sourceSets.main.runtimeClasspath
    }

    hideservermessages {
        compileClasspath += sourceSets.main.compileClasspath
        runtimeClasspath += sourceSets.main.runtimeClasspath
		}
}

dependencies {
    minecraft "com.mojang:minecraft:1.21.1"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:0.16.10"
    modImplementation "net.fabricmc.fabric-api:fabric-api:0.115.3+1.21.1"
    
    modImplementation files("deps/bobby-5.2.4+mc1.21.jar")
    modLocalRuntime files([
            //bobby JiJs
            "deps/config-1.4.2.jar",
            "deps/configurate-core-4.1.2.jar",
            "deps/configurate-hocon-4.1.2.jar",
            "deps/geantyref-1.3.13.jar",
            
            //templates (for testing bobbyallowlist)
            "deps/templates-mod-2.5.0+1.21.1.jar",
    ])
    
    //todo do this inside the sourcesets loop below...
    spectatorheadsImplementation sourceSets.main.output
    bobbyallowlistImplementation sourceSets.main.output
    quickfovImplementation sourceSets.main.output
    hideservermessagesImplementation sourceSets.main.output
}

loom {
    mixin {
        add(sourceSets.main, "oneoffs-lib.refmap.json") //dont think this is used atm since oneoffs-lib doesn't define any refmaps
        //" Failed to find mixin mappings mixin-map-loom.mappings.1_21_1.layered+hash.2198-v2.test.tiny in task outputs: task 'compileTestJava' output files "
        //yeah i'd hope so
        add(sourceSets.test, "oneoffs-lib-test-somehow.refmap.json")
    }
}

//breaking this out into a function
Action<ProcessResources> configureProcessResources = {
    it.inputs.property "version", project.version
    it.filesMatching(["**/fabric.mod.json"]) {
        expand "version": project.version
    }
}

//root jar processResources
tasks.named("processResources").configure configureProcessResources

[
        sourceSets.spectatorheads,
        sourceSets.bobbyallowlist,
        sourceSets.quickfov,
        sourceSets.hideservermessages,
].each { set ->
    println "thinkin bout ${set.name}"
    
    def myBaseName = "oneoffs-${set.name}"
    
    loom {
        mixin {
            add(set, "oneoffs-${set.name}.refmap.json")
        }
    }
    
    //add to loom run config classpath, just blindly copying loom rungametask here
    //there's maybe a better classpath property to use :thinking:
    tasks.withType(AbstractRunTask.class).configureEach {
        it.internalClasspath.from set.runtimeClasspath
    }
    
    //set up processResources for this srcset
    //TODO whats the right way to find the processResources task lol
    tasks.named("process${set.name.capitalize()}Resources").configure configureProcessResources
    
    //devjar task
    def setJarTask = tasks.register("${set.name}Jar", Jar) {
        it.archiveBaseName = myBaseName
        from set.output
        //https://github.com/FabricMC/fabric-loom/blob/ebc638f2865141bd8ce1ce26d6a05849ec771946/src/main/java/net/fabricmc/loom/task/RemapTaskConfiguration.java#L102
        it.archiveClassifier = "dev"
        it.destinationDirectory = tasks.jar.destinationDirectory
    }
    
    //distjar task
    def setRemapTask = tasks.register("${set.name}Remap", RemapJarTask) {
        it.archiveBaseName = myBaseName
        it.dependsOn setJarTask
        it.input = setJarTask.flatMap({ it.getArchiveFile() })
    }
    
    artifacts {
        namedElements setJarTask
        
        apiElements setRemapTask
        runtimeElements setRemapTask
    }
    
    //hang these tasks off corresponding tasks from the main sourceset
    //mainly so "./gradlew build" builds everything, and you don't need a buildAll or whatev
    tasks.named("jar").configure { it.dependsOn setJarTask }
    tasks.named("assemble").configure { it.dependsOn setRemapTask }
}
